AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI-Powered EHR Imaging & Documentation System - AWS Infrastructure

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production

Resources:
  # S3 Bucket for Medical Images
  MedicalImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'ehr-medical-images-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  # DynamoDB Table for Patient Records
  PatientRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ehr-patient-records
      AttributeDefinitions:
        - AttributeName: patient_id
          AttributeType: S
        - AttributeName: note_id
          AttributeType: S
      KeySchema:
        - AttributeName: patient_id
          KeyType: HASH
        - AttributeName: note_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # IAM Role for Lambda Functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: '*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${MedicalImagesBucket.Arn}/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt PatientRecordsTable.Arn

  # Lambda Layer for Dependencies
  PythonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ehr-python-dependencies
      Description: Python dependencies for EHR Lambda functions
      ContentUri: ../backend/layers/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain

  # Lambda Function: Image Enhancement
  ImageEnhancementFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ehr-image-enhancement
      CodeUri: ../backend/lambda_functions/
      Handler: image_enhancement.lambda_handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 2048
      Role: !GetAtt LambdaExecutionRole.Arn
      Layers:
        - !Ref PythonDependenciesLayer
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
          S3_BUCKET_NAME: !Ref MedicalImagesBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /image-enhancement
            Method: POST

  # Lambda Function: Clinical Notes
  ClinicalNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ehr-clinical-notes
      CodeUri: ../backend/lambda_functions/
      Handler: clinical_notes_generator.lambda_handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 1024
      Role: !GetAtt LambdaExecutionRole.Arn
      Layers:
        - !Ref PythonDependenciesLayer
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
          DYNAMODB_TABLE_NAME: !Ref PatientRecordsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /clinical-notes
            Method: POST

  # Lambda Function: ICD-10 Coding
  ICD10CodingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ehr-icd10-coding
      CodeUri: ../backend/lambda_functions/
      Handler: icd10_coding.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt LambdaExecutionRole.Arn
      Layers:
        - !Ref PythonDependenciesLayer
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /icd10-coding
            Method: POST

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ehr-ai-api
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: NONE

  # CloudWatch Log Groups
  ImageEnhancementLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ImageEnhancementFunction}'
      RetentionInDays: 14

  ClinicalNotesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ClinicalNotesFunction}'
      RetentionInDays: 14

  ICD10CodingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ICD10CodingFunction}'
      RetentionInDays: 14

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  MedicalImagesBucketName:
    Description: S3 bucket for medical images
    Value: !Ref MedicalImagesBucket
    Export:
      Name: !Sub '${AWS::StackName}-ImagesBucket'

  PatientRecordsTableName:
    Description: DynamoDB table for patient records
    Value: !Ref PatientRecordsTable
    Export:
      Name: !Sub '${AWS::StackName}-PatientTable'

  LambdaExecutionRoleArn:
    Description: IAM Role ARN for Lambda functions
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRole'
