AWSTemplateFormatVersion: '2010-09-09'
Description: EHR AI System - Simplified Deployment

Resources:
  # S3 Bucket for Medical Images
  MedicalImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'ehr-medical-images-'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST]
            AllowedOrigins: ['*']

  # DynamoDB Table
  PatientRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ehr-patient-records
      AttributeDefinitions:
        - AttributeName: patient_id
          AttributeType: S
        - AttributeName: note_id
          AttributeType: S
      KeySchema:
        - AttributeName: patient_id
          KeyType: HASH
        - AttributeName: note_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # IAM Role for Lambda
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['bedrock:*']
                Resource: '*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['s3:*']
                Resource:
                  - !GetAtt MedicalImagesBucket.Arn
                  - !Sub '/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['dynamodb:*']
                Resource: !GetAtt PatientRecordsTable.Arn

  # Lambda: Image Enhancement
  ImageEnhancementFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ehr-image-enhancement
      Runtime: python3.11
      Handler: image_enhancement.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 60
      MemorySize: 2048
      Code:
        S3Bucket: ehr-deployment-340663646697
        S3Key: lambda-package.zip
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
          S3_BUCKET_NAME: !Ref MedicalImagesBucket

  # Lambda: Clinical Notes
  ClinicalNotesFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ehr-clinical-notes
      Runtime: python3.11
      Handler: clinical_notes_generator.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 60
      MemorySize: 1024
      Code:
        S3Bucket: ehr-deployment-340663646697
        S3Key: lambda-package.zip
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
          DYNAMODB_TABLE_NAME: !Ref PatientRecordsTable

  # Lambda: ICD-10 Coding
  ICD10CodingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ehr-icd10-coding
      Runtime: python3.11
      Handler: icd10_coding.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 30
      MemorySize: 512
      Code:
        S3Bucket: ehr-deployment-340663646697
        S3Key: lambda-package.zip
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ehr-ai-api
      Description: EHR AI System API

  # API Gateway Resource - Image Enhancement
  ImageEnhancementResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: image-enhancement

  # API Gateway Method - Image Enhancement
  ImageEnhancementMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ImageEnhancementResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway::lambda:path/2015-03-31/functions//invocations'

  # Lambda Permission - Image Enhancement
  ImageEnhancementPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ImageEnhancementFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:::/*'

  # API Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ImageEnhancementMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

Outputs:
  ApiUrl:
    Value: !Sub 'https://.execute-api..amazonaws.com/prod'
  ImagesBucket:
    Value: !Ref MedicalImagesBucket
  PatientTable:
    Value: !Ref PatientRecordsTable
